/*
 qyt create sql file
*/


CREATE DATABASE `XEngine_MQData` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8mb4_general_ci;
CREATE DATABASE `XEngine_MQUser` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8mb4_general_ci;